---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: "${image:-centos7}"
    image: "${namespace:-geerlingguy}/docker-${image:-centos7}-ansible:${tag:-latest}"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes

provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
