---
- name: Prepare
  hosts: all
  tasks:
    - name: install gpg-agent
      apt:
        name: gpg-agent
        update_cache: yes
        install_recommends: no
        state: present
      when:
        - ansible_os_family == 'Debian'