# This is a basic workflow to help you get started with Actions

name: Ansible Molecule Check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@2.6.1
        with:
          command: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - image: "centos7"
          - image: "centos8"
          - image: "ubuntu1804"
          - image: "ubuntu2004"
          - image: "debian10"
          - image: "debian11"
          - image: "rockylinux8"
          
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@2.6.1
        with:
          image: "${{ matrix.config.image }}"
          namespace: "geerlingguy"
          options: parallel
